### ISSUE TITLE
undefined method `reset' for #<ActiveSupport::Logger

### ISSUE THREAD

**Issue by entropywtf** [dwbutler/logstash-logger#151]
Hi,
Following the documentation, I put Rails.logger.reset into config/puma.rb

On server start though, I get an error:

`undefined method `reset' for #<ActiveSupport::Logger:0x00007f932cfdb148>	 6: from /Users/marina/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/puma-3.12.0/lib/puma/cluster.rb:137:in `fork'
 (NoMethodError (	 5: from /Users/marina/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/puma-3.12.0/lib/puma/cluster.rb:137:in `block (2 levels) in spawn_workers'
NoMethodErrorNoMethodError)`

And indeed, Rails.logger.methods.grep(/reset/) does return an empty array. Did you mean to use #flush here?

Thanks and sorry if I'm missing something obvious here. KR

**Comment by entropywtf** [comment]
After looking closer and going through merged PRs I found out that reset method was exposed and it is actually a feature, BUT:

If you run into this error, you still have Rails.logger not set to Logstash. If Logstash logging is conditional in your application, you better put Rails.logger.reset under a condition like` if respond_to?(:reset)` or `if ENV['LOGSTASH_ENABLED']` like I did in my project.

I'd suggest to put this advice into a README.

Thanks!

**Comment by bv-ritesh** [comment]
In case of multilogger, the instance does not respond to reset method.
```
logger.logger.each { |_logger|
 _logger.respond_to?(:reset)
}
```

This will work

**Comment by dwbutler** [comment]
Fixed in #153
