### ISSUE TITLE
ERROR -- : [LogStashLogger::Device::TCP] OpenSSL::SSL::SSLError - SSL_connect SYSCALL returned=5 errno=0 state=unknown state

### ISSUE THREAD

**Issue by stephanlindauer** [dwbutler/logstash-logger#93]
my client code:

```
require 'logstash-logger'
require 'sys/filesystem'

logger = LogStashLogger.new(type: :tcp,
                            host: 'logstash.bla.com',
                            port: 5228,
                            ssl_certificate: "ssl/logstash.crt")

logger.error '{"message": "test"}'
```

my logstash.conf

```
input {
  tcp {
    host => "0.0.0.0"
    port => 5228
    # codec => json_lines
    ssl_enable => true
    ssl_cert => "/etc/logstash/ssl/logstash.crt"
    ssl_key => "/etc/logstash/ssl/logstash.key"
  }
}

output {
    elasticsearch {
        hosts => "elasticsearch:9200"
    index => "logstash-%{+YYYY.MM.dd}"
    }
}
```

cert and key were generated with 

```
openssl req -x509 -batch -nodes -newkey rsa:2048 -keyout logstash.key -out logstash.crt
```

however, when i try to connect from logstash-logger, i get 

```
ERROR -- : [LogStashLogger::Device::TCP] OpenSSL::SSL::SSLError - SSL_connect SYSCALL returned=5 errno=0 state=unknown state
```

logstash version: 2.3
ruby version 2.2.3

**Comment by stephanlindauer** [comment]
in logstash with --debug, i get:
```
logstash_1          | {:timestamp=>"2016-08-16T15:58:46.970000+0000", :message=>"SSL Error", :exception=>#<OpenSSL::SSL::SSLError: null cert chain>, :backtrace=>["org/jruby/ext/openssl/SSLSocket.java:272:in `accept'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/jruby-openssl-0.9.13-java/lib/jopenssl19/openssl/ssl-internal.rb:106:in `accept'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-tcp-3.0.6/lib/logstash/inputs/tcp.rb:112:in `run_server'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-tcp-3.0.6/lib/logstash/inputs/tcp.rb:84:in `run'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.4-java/lib/logstash/pipeline.rb:342:in `inputworker'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.4-java/lib/logstash/pipeline.rb:336:in `start_input'"], :level=>:debug, :file=>"logstash/inputs/tcp.rb", :line=>"117", :method=>"run_server"}

```

**Comment by steviee** [comment]
Hi @stephanlindauer,

any progress on this one?
I do also have this exact same problem.

Best regards,
Stephan

**Comment by stephanlindauer** [comment]
unfortunately not.

**Comment by steviee** [comment]
I have a feeling that there's a bug somewhere in how logstash-logger uses OpenSSL::SSLSocket... Maybe one needs a differently generated certificate or something.

Not sure...

**Comment by stephanlindauer** [comment]
i did some more testing on this. i have my ruby code in one docker file and logstash in another.
i checked the linkage between those two containers: works
i realized i had to open permissions on my ssl files so i fixed that wil ```chmod 400```.
still i can't get that whole thing to work though.
